# Dependencies
markdown:         redcarpet
kramdown: 
  input: GFM
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Koheron
tagline:          'Blog'
description:      'Smart instruments'
url:              
#baseurl:          http://jeanminet.github.io/lanyon/

comments:          false

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/jeanminet/lanyon
